version: '3'
services:
  redis: 
    image: 'redis'
  dev:
    image: 'node:latest'
    depends_on:
      - redis
    environment:
      - PORT=8000
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    working_dir: /app
    command: yarn dev
  prod:
    build: '.'
    depends_on:
      - redis
    environment:
      - PORT=8000
    ports:
      - "80:8000"
